### PR TITLE
fix: update sqlx to 0.6

### LINKED ISSUE #10: trait bound `Postgres: sqlx_core::database::Database` is not satisfied
When running [this repo](https://github.com/PXNX/tartaros-telegram), I get the following error:

```
error[E0277]: the trait bound `Postgres: sqlx_core::database::Database` is not satisfied
  --> src/main.rs:51:13
   |
51 |     mut tx: Tx<Postgres>,
   |             ^^^^^^^^^^^^ the trait `sqlx_core::database::Database` is not implemented for `Postgres`
   |
   = help: the trait `sqlx_core::database::Database` is implemented for `sqlx_core::postgres::database::Postgres`
note: required by a bound in `Tx`
  --> /home/nyx/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-sqlx-tx-0.3.0/src/tx.rs:75:19
   |
75 | pub struct Tx<DB: sqlx::Database, E = Error>(Lease<sqlx::Transaction<'static, DB>>, PhantomData<E>);
   |                   ^^^^^^^^^^^^^^ required by this bound in `Tx`
```
   
   Is this a bug or something I can solve myself? If the latter, how may I do that?

### PR DESCRIPTION
**Pull request by greizgh**
This will closes #10

### CODE REVIEW

**Comment by sedrik** [comment]
Would it make sense to upgrade to 0.6.1 now that it is out? :)

**Comment by greizgh** [comment]
> Would it make sense to upgrade to 0.6.1 now that it is out? :)

The constraint has been changed to "0.6", so it will accept "0.6.1" and any other "0.6.x" version.
Since this crate is used as a lib, my understanding is that it should accept the lowest possible version ("0.6.0") and not have strict constraint to match applications' one. That is, if at some point in my app I have sqlx 0.6.5, I want the lib to use 0.6.5 (that is, unless there is a missing feature or breaking change, which doesn't seem to be the case here).

**Comment by sedrik** [comment]
Ah yes, my bad :)

**Comment by connec** [comment]
Oh thanks for this! I'll take a look at it very soon. Notifications for this project are turned off for some reason 😅

**Comment by connec** [comment]
Thank you. I'll follow this up with a release imminently.

**Pull request merged**
